-- AlterTable
ALTER TABLE "Attendance" ADD COLUMN     "is_pelindo_friday" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "is_pelindo_monday" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "is_pelindo_saturday" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "is_pelindo_sunday" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "is_pelindo_thursday" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "is_pelindo_tuesday" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "is_pelindo_wednesday" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "late_pelindo_max_time_friday" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "late_pelindo_max_time_monday" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "late_pelindo_max_time_saturday" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "late_pelindo_max_time_sunday" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "late_pelindo_max_time_thursday" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "late_pelindo_max_time_tuesday" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "late_pelindo_max_time_wednesday" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "late_pelindo_min_time_friday" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "late_pelindo_min_time_monday" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "late_pelindo_min_time_saturday" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "late_pelindo_min_time_sunday" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "late_pelindo_min_time_thursday" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "late_pelindo_min_time_tuesday" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "late_pelindo_min_time_wednesday" INTEGER NOT NULL DEFAULT 0;
