services:
  app:
    image: absen:latest
    container_name: be-absen
    ports:
      - '8500:8500'
    user: '1000:1000'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    restart: always
    volumes:
      - /home/dimasaulia/docker_volumes/absen_storage:/usr/src/app/src/public/img/storage
