import { z, ZodType } from 'zod';

export class AttendanceValidation {
  static readonly ADD_ATTENDANCE: ZodType = z.object({
    via: z.string().min(3),
    kondisi: z.string().min(0),
    attendance_eoffice_on_sunday: z.boolean(),
    attendance_eoffice_on_monday: z.boolean(),
    attendance_eoffice_on_tuesday: z.boolean(),
    attendance_eoffice_on_wednesday: z.boolean(),
    attendance_eoffice_on_thursday: z.boolean(),
    attendance_eoffice_on_friday: z.boolean(),
    attendance_eoffice_on_saturday: z.boolean(),
    attendance_pelindo_on_sunday: z.boolean(),
    attendance_pelindo_on_monday: z.boolean(),
    attendance_pelindo_on_tuesday: z.boolean(),
    attendance_pelindo_on_wednesday: z.boolean(),
    attendance_pelindo_on_thursday: z.boolean(),
    attendance_pelindo_on_friday: z.boolean(),
    attendance_pelindo_on_saturday: z.boolean(),
    min_eoffice_time_sunday: z.number(),
    min_eoffice_time_monday: z.number(),
    min_eoffice_time_tuesday: z.number(),
    min_eoffice_time_wednesday: z.number(),
    min_eoffice_time_thursday: z.number(),
    min_eoffice_time_friday: z.number(),
    min_eoffice_time_saturday: z.number(),
    max_eoffice_time_sunday: z.number(),
    max_eoffice_time_monday: z.number(),
    max_eoffice_time_tuesday: z.number(),
    max_eoffice_time_wednesday: z.number(),
    max_eoffice_time_thursday: z.number(),
    max_eoffice_time_friday: z.number(),
    max_eoffice_time_saturday: z.number(),
    min_pelindo_time_sunday: z.number(),
    min_pelindo_time_monday: z.number(),
    min_pelindo_time_tuesday: z.number(),
    min_pelindo_time_wednesday: z.number(),
    min_pelindo_time_thursday: z.number(),
    min_pelindo_time_friday: z.number(),
    min_pelindo_time_saturday: z.number(),
    max_pelindo_time_sunday: z.number(),
    max_pelindo_time_monday: z.number(),
    max_pelindo_time_tuesday: z.number(),
    max_pelindo_time_wednesday: z.number(),
    max_pelindo_time_thursday: z.number(),
    max_pelindo_time_friday: z.number(),
    max_pelindo_time_saturday: z.number(),
    location_sunday: z.number(),
    location_monday: z.number(),
    location_tuesday: z.number(),
    location_wednesday: z.number(),
    location_thursday: z.number(),
    location_friday: z.number(),
    location_saturday: z.number(),
  });
}
